<?php

namespace Modules\Frontend\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HomepageCtaSeeder extends Seeder
{
    public function run()
    {
        // Delete all existing CTAs first
        DB::table('homepage_ctas')->truncate();

        DB::table('homepage_ctas')->insert([
            // Style 1: Standard - Left aligned with image
            [
                'cta_style'                => 'style1',
                'title'                    => 'Summer Deals For You',
                'subtitle'                 => 'Discounts on top products',
                'description'              => 'Shop our biggest sale of the year on electronics, fashion, and home essentials. Limited time offer!',
                'image'                    => null,
                'banner_image'             => null,
                'button_text'              => 'Shop Now',
                'button_link'              => '/sale/summer',
                'background_color'         => '#fee2e2',
                'text_color'               => '#991b1b',
                'button_color'             => '#dc2626',
                'button_text_color'        => '#ffffff',
                'overlay_color'            => null,
                'badge_text'               => null,
                'badge_color'              => null,
                'secondary_button_text'    => null,
                'secondary_button_link'    => null,
                'secondary_button_color'   => null,
                'secondary_button_text_color' => null,
                'feature_icon_1'           => null,
                'feature_text_1'           => null,
                'feature_icon_2'           => null,
                'feature_text_2'           => null,
                'feature_icon_3'           => null,
                'feature_text_3'           => null,
                'sort_order'               => 0,
                'status'                   => 'active',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],

            // Style 2: Banner with overlay
            [
                'cta_style'                => 'style2',
                'title'                    => 'Premium Collection 2026',
                'subtitle'                 => 'Discover luxury at its finest',
                'description'              => 'Curated premium products from top brands worldwide. Elevate your lifestyle today.',
                'image'                    => null,
                'banner_image'             => null,
                'button_text'              => 'Explore Collection',
                'button_link'              => '/category/premium',
                'background_color'         => '#1e1b4b',
                'text_color'               => '#ffffff',
                'button_color'             => '#f59e0b',
                'button_text_color'        => '#1e1b4b',
                'overlay_color'            => 'rgba(0,0,0,0.5)',
                'badge_text'               => 'Limited Edition',
                'badge_color'              => '#ef4444',
                'secondary_button_text'    => null,
                'secondary_button_link'    => null,
                'secondary_button_color'   => null,
                'secondary_button_text_color' => null,
                'feature_icon_1'           => null,
                'feature_text_1'           => null,
                'feature_icon_2'           => null,
                'feature_text_2'           => null,
                'feature_icon_3'           => null,
                'feature_text_3'           => null,
                'sort_order'               => 1,
                'status'                   => 'active',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],

            // Style 3: Centered with badge
            [
                'cta_style'                => 'style3',
                'title'                    => 'Flash Sale Weekend',
                'subtitle'                 => 'Up to 70% off',
                'description'              => 'Huge discounts on thousands of items. This weekend only — don\'t miss out on incredible savings!',
                'image'                    => null,
                'banner_image'             => null,
                'button_text'              => 'Grab the Deals',
                'button_link'              => '/sale/flash',
                'background_color'         => '#fef3c7',
                'text_color'               => '#92400e',
                'button_color'             => '#f59e0b',
                'button_text_color'        => '#ffffff',
                'overlay_color'            => null,
                'badge_text'               => '🔥 Hot Sale',
                'badge_color'              => '#ef4444',
                'secondary_button_text'    => null,
                'secondary_button_link'    => null,
                'secondary_button_color'   => null,
                'secondary_button_text_color' => null,
                'feature_icon_1'           => null,
                'feature_text_1'           => null,
                'feature_icon_2'           => null,
                'feature_text_2'           => null,
                'feature_icon_3'           => null,
                'feature_text_3'           => null,
                'sort_order'               => 2,
                'status'                   => 'active',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],

            // Style 4: Split layout with dual buttons
            [
                'cta_style'                => 'style4',
                'title'                    => 'New Arrivals Are Here',
                'subtitle'                 => 'Fresh styles, fresh vibes',
                'description'              => 'Be the first to explore our newest collection. From casual wear to formal attire, find your perfect look.',
                'image'                    => null,
                'banner_image'             => null,
                'button_text'              => 'Shop New In',
                'button_link'              => '/new-arrivals',
                'background_color'         => '#ecfdf5',
                'text_color'               => '#065f46',
                'button_color'             => '#059669',
                'button_text_color'        => '#ffffff',
                'overlay_color'            => null,
                'badge_text'               => 'Just Landed',
                'badge_color'              => '#3b82f6',
                'secondary_button_text'    => 'Learn More',
                'secondary_button_link'    => '/about',
                'secondary_button_color'   => '#ffffff',
                'secondary_button_text_color' => '#059669',
                'feature_icon_1'           => null,
                'feature_text_1'           => null,
                'feature_icon_2'           => null,
                'feature_text_2'           => null,
                'feature_icon_3'           => null,
                'feature_text_3'           => null,
                'sort_order'               => 3,
                'status'                   => 'active',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],

            // Style 5: Features grid with CTA
            [
                'cta_style'                => 'style5',
                'title'                    => 'Why Shop With Us',
                'subtitle'                 => 'The best shopping experience',
                'description'              => 'We are committed to providing you with the best online shopping experience possible.',
                'image'                    => null,
                'banner_image'             => null,
                'button_text'              => 'Start Shopping',
                'button_link'              => '/products',
                'background_color'         => '#f0f9ff',
                'text_color'               => '#1e3a8a',
                'button_color'             => '#1e3a8a',
                'button_text_color'        => '#ffffff',
                'overlay_color'            => null,
                'badge_text'               => 'Trusted by 10K+',
                'badge_color'              => '#8b5cf6',
                'secondary_button_text'    => null,
                'secondary_button_link'    => null,
                'secondary_button_color'   => null,
                'secondary_button_text_color' => null,
                'feature_icon_1'           => '🚚',
                'feature_text_1'           => 'Free Shipping on orders over $50',
                'feature_icon_2'           => '🔒',
                'feature_text_2'           => 'Secure Payment with SSL encryption',
                'feature_icon_3'           => '💬',
                'feature_text_3'           => '24/7 Customer Support',
                'sort_order'               => 4,
                'status'                   => 'active',
                'created_at'               => now(),
                'updated_at'               => now(),
            ],
        ]);
    }
}