<x-app-layout>
    <div class="p-6 space-y-6" x-data="campaignManager()" x-init="load()">
        <div class="flex items-center justify-between"><div><h1 class="text-2xl font-bold">Campaigns</h1><p class="text-sm text-gray-500">Create product offers and manage their active dates.</p></div></div>
        <div class="grid lg:grid-cols-3 gap-6"><form @submit.prevent="create()" class="bg-white rounded-xl border p-5 space-y-3"><h2 class="font-semibold">New campaign</h2><input x-model="form.name" required placeholder="Campaign name" class="w-full rounded border-gray-300"><textarea x-model="form.description" placeholder="Description" class="w-full rounded border-gray-300"></textarea><input x-model="form.banner_image" placeholder="Banner image path (optional)" class="w-full rounded border-gray-300"><div class="grid grid-cols-2 gap-2"><input x-model="form.starts_at" type="datetime-local" class="rounded border-gray-300"><input x-model="form.ends_at" type="datetime-local" class="rounded border-gray-300"></div><select x-model="form.status" class="w-full rounded border-gray-300"><option value="draft">Draft</option><option value="active">Active</option><option value="paused">Paused</option></select><button class="px-4 py-2 rounded bg-primary text-white">Create campaign</button></form><div class="lg:col-span-2 space-y-3"><template x-for="campaign in campaigns" :key="campaign.id"><div class="bg-white border rounded-xl p-4"><div class="flex justify-between"><div><p class="font-semibold" x-text="campaign.name"></p><p class="text-xs text-gray-500"><span x-text="campaign.status"></span> · <span x-text="campaign.products_count"></span> products</p></div><button @click="select(campaign.id)" class="text-primary text-sm">Manage products</button></div></div></template><p x-show="!campaigns.length" class="text-gray-500 text-sm">No campaigns yet.</p></div></div>
        <div x-show="selected" class="bg-white rounded-xl border p-5 space-y-4"><h2 class="font-semibold">Add products to campaign</h2><div class="flex gap-2"><input @input.debounce.300ms="searchProducts($event.target.value)" placeholder="Search product name..." class="flex-1 rounded border-gray-300"><select x-model="discount_type" class="rounded border-gray-300"><option value="percentage">Percent</option><option value="fixed_amount">Fixed off</option><option value="fixed_price">Fixed price</option></select><input x-model="discount_value" type="number" min="0" step="0.01" placeholder="Discount" class="w-28 rounded border-gray-300"></div><template x-for="product in searchResults" :key="product.id"><div class="flex justify-between items-center border-t py-2"><span x-text="product.name"></span><button @click="addProduct(product.id)" class="text-primary text-sm">Add</button></div></template><template x-if="selectedData"><div class="border-t pt-3"><p class="text-sm font-medium mb-2">Included products</p><template x-for="item in selectedData.products" :key="item.id"><div class="flex justify-between text-sm py-1"><span x-text="item.product.name + ' — ' + item.discount_value + ' ' + item.discount_type"></span><button @click="removeProduct(item.id)" class="text-red-500">Remove</button></div></template></div></template></div>
    </div>
    <script>
        function campaignManager() { const csrf = document.querySelector('meta[name=csrf-token]').content; const request = (url, options={}) => fetch(url,{headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf,'Accept':'application/json'},...options}).then(r=>r.json()); return { campaigns:[], selected:null, selectedData:null, searchResults:[], discount_type:'percentage', discount_value:'', form:{name:'',description:'',banner_image:'',starts_at:'',ends_at:'',status:'draft'}, load(){request('{{ route('campaigns.list') }}').then(d=>this.campaigns=d.campaigns)}, create(){request('{{ route('campaigns.store') }}',{method:'POST',body:JSON.stringify(this.form)}).then(()=>{this.form={name:'',description:'',banner_image:'',starts_at:'',ends_at:'',status:'draft'};this.load()})}, select(id){this.selected=id;request('/campaigns/'+id).then(d=>this.selectedData=d.campaign)}, searchProducts(q){if(q.length<2){this.searchResults=[];return}request('{{ route('campaigns.products.search') }}?q='+encodeURIComponent(q)).then(d=>this.searchResults=d.products)}, addProduct(product_id){if(!this.discount_value)return;request('/campaigns/'+this.selected+'/products',{method:'POST',body:JSON.stringify({product_id,discount_type:this.discount_type,discount_value:this.discount_value})}).then(()=>this.select(this.selected))}, removeProduct(id){request('/campaigns/'+this.selected+'/products/'+id,{method:'DELETE'}).then(()=>this.select(this.selected))} } }
    </script>
</x-app-layout>
